<?php

namespace IUT\AdminBundle\Repository;

/**
 * CoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinsRepository extends \Doctrine\ORM\EntityRepository
{
}
